# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Git

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/3 * * * *'
    
permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"
          
      - name: checkout repo content
        uses: actions/checkout@v4        
          
      #- name: commit 1
      #  run: |
      #    # setup git
      #    git config --local user.name "GitHub Actions Bot"
      #    git config --local user.email "<>"
      #    git add -A
      #    timestamp=$(date)
      #    git commit -m "Latest data: ${timestamp}" || exit 0
      #    git push
          
          
      - name: commit
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "<>"
          git remote add demo2 https://github.com/white5168/taifex
          git remote -v
          git add pcratio.png
          timestamp=$(date)
          git commit -m "Latest data: ${timestamp}" || exit 0

          git push demo2
