name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/3 * * * *'
    
permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"

      - name: checkout repo content
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml
          pip install -r requirements.txt

      - name: Remove file and dir
        run: |
          list="pcratio.png README.md"
          for i in $list; do
            if [ -f ${i} ]; then
              rm ${i}
            fi
          done
          
          if [-d "taifex"]; then
            rm -f taifex/*.* taifex/*
            rmdir taifex
          fi
  
      - name: execute py script
        run: |
          python taifex.py

      - name: Configure Git
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDD-HHmmSS
          utcOffset: "+08:00"
          
      - name: commit local repository
        run: |
          # setup git
          git add -A
          git commit -m "更新時間: ${{ steps.current-time.outputs.formattedTime }}" || exit 0
          git push

      - name: Clone target repository
        run: git clone https://github.com/white5168/taifex.git

      - name: Move files to target repository
        run: |
          cp pcratio.png taifex
          cp README.md taifex
          cd taifex
          git add .
          git commit -m "更新時間: ${{ steps.current-time.outputs.formattedTime }}"
          git push https://white5168:${{secrets.ACCESS_GITHUB_TOKEN}}@github.com/white5168/taifex.git          
