# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"
          
      - name: checkout repo content
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install -r requirements.txt
          
      - name: execute py script
        run: |
          python taifex.py
          
      - name: setup git config
        run: |
          # setup git
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      #- name: commit
      #  run: |
          # Stage the file, commit and push
          #git add results.csv
          #git commit -m "update results"
          #git push origin main
