name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/3 * * * *'
    
permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"

      - name: checkout repo content
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml
          pip install -r requirements.txt

      - name: Remove file and dir
        run: |
          list="pcratio.png README.md"
          for i in $list; do
            if [ -f ${i} ]; then
              rm ${i}
            fi
          done
          
          if [-d "tmp"]; then
            rm -f tmp/*.* tmp/*
            rmdir tmp
          fi
          
      - name: Execute py script
        run: |
          python taifex.py
          
      - name: Configure Git
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
       
      - name: Commit local repository
        run: |
          # setup git
          git add -A
          timestamp=$(date)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: white5168/taifex
          token: ${{ secrets.ACCESS_GITHUB_TOKEN }} 

      - name: Commit and push changes
        run: |
          #mkdir tmp
          #cp pcratio.png tmp
          #cp README.md tmp
          #cd tmp
          git add .
          timestamp=$(date)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
