# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/3 * * * *'
    
permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"
          
      - name: checkout repo content
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml
          pip install -r requirements.txt
          
      - name: execute py script 1
        run: |
          python taifex.py
          
      - name: commit 1
        run: |
          # setup git
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "<>"
          git add -A
          timestamp=$(date)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
          
      - name: execute py script 2
        run: |
          python taifex.py
          
      - name: commit 2
        run: |
          git remote remove origin
          #git remote set-url origin https://github.com/white5168/taifex.git
          git remote add origin https://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@github.com/white5168/taifex.git
          git add -A
          timestamp=$(date)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git branch -M main
          git push -u origin main
          
      #- name: commit
      #  run: |
          # Stage the file, commit and push
      #    git add pcratio.png
      #    git commit -m "update results"
      #    git push origin main
